### ISSUE TITLE
Events conducted in September 2016

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#1]

**Comment by shahbaz17** [comment]
Name of Event : Virtual day @ Mozunicorn
Date : 09 Sept. , 2016
Reps Portal link : https://reps.mozilla.org/e/virtual-day-mozunicorn/

**Comment by gurumukhi** [comment]
Thanks @shahbaz17 for reporting 👍 This is now featured on https://wiki.mozilla.org/India/WebVR/.
