### ISSUE TITLE
Events conducted in November 2016

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#10]
This issue is created to report contributions done by volunteers in this month. While reporting about your event please use the following format:

**Name               : 
Event Name     :
Event Date       : 
Event Location : 
Event Link        :**

**Comment by vibhanshuchaudhary** [comment]
**Name :** Vibhanshu Chaudhary
**Event Name :** A Day of Virtual Reality
**Event Date :** 7 November 2016
**Event Location :** Greater Noida
**Event Link :** https://reps.mozilla.org/e/a-day-of-virtual-reality/

**Comment by shahbaz17** [comment]
Name : Md Shahbaz Alam and Osho Parth
Event Name : MozDev @ NIIT
Event Date : 12 November 2016
Event Location : NIIT University Neemrana , Rajasthan
Event Link : https://reps.mozilla.org/e/mozdev-niit/

**Comment by varadekd** [comment]
Name : Kushagra Varade and Vaibhav Bajaj
Event Name : MozVR Camp Bhopal
Event Date : 10 Nov 2016
Event Location : UIT,RGPV, Bhopal, Madhya Pradesh
Event Link : https://reps.mozilla.org/e/vr-camp-bhopal/

**Comment by vabajaj** [comment]
Name : Vaibhav Bajaj         
Event Name : MozVR Camp Bhopal
Event Date : 20 Nov 2016
Event Location : LNCT College , Bhopal, Madhya Pradesh
Event Link : https://reps.mozilla.org/e/mozvr-camp-bhopal/

**Comment by rahuldecoded** [comment]
Name : Rahul Bhattacharjee
Event Name : MozVR at UIT
Event Date : 25 Nov 2016
Event Location : University Institute of Technology, Burdwan
Event Link : https://reps.mozilla.org/e/mozactivate-tour/

**Comment by shahbaz17** [comment]
Thanks all for reporting :+1: This is now featured on https://wiki.mozilla.org/India/WebVR/#Events
