### ISSUE TITLE
Projects/Scenes created in November 2016

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#11]
This issue is created to report contributions done by volunteers in this month. While sharing your scenes/projects with us, please follow the following format : 

**Name : 
Name of Project / Scene : 
Link of Project / Scene :**

**Comment by Srushtika** [comment]
Name of the Scene: Hello World application covering the basic primitives in A-Frame
Link of the Scene: https://srushtika.github.io/mywebvr/Hello%20World/index.html

**Comment by Srushtika** [comment]
Name of the Scene: Let's go places ! - Content display website in VR using A-Frame
Link to the Scene: https://srushtika.github.io/mywebvr/ContentDisplayWebsite/index.html

**Comment by mukeshpathak345** [comment]
Name of the Scene: 360 Video using Basic A-Frame
Link to the Scene: [](https://mukeshpathak345.github.io/360-video/)

**Comment by mukeshpathak345** [comment]
Name of the Scene: MozMicky Sonam-Gupta Bewafa hai A-frame
Link to the Scene: https://mukeshpathak345.github.io/Sonal-GuptaVr/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak  Mike
Name of Project / Scene : VR scene using sphere and a sky
Link of Project / Scene : https://mukeshpathak345.github.io/mozmicky.webvr.io/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak Mike
Name of Project / Scene : 360 Round Images VR scene using Image Round 360 
Link of Project / Scene : https://mukeshpathak345.github.io/moz-webVR/

**Comment by Srushtika** [comment]
Name of the Scene: Rainy Day - VR Scenery
Link to the Scene: https://srushtika.github.io/mywebvr/VR%20Scenery/index.html

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak Mike
Name of Project / Scene : MozMicky Audio Horror
Link of Project / Scene : https://mukeshpathak345.github.io/horror-theme/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak
Name of Project / Scene : Ice-Star-Rain
Link of Project / Scene :  https://mukeshpathak345.github.io/Ice-Star-Rain/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak
Name of Project / Scene : WebVR-Aframe
Link of Project / Scene : https://mukeshpathak345.github.io/mozilla-webvr/

**Comment by rahuldecoded** [comment]
Name : Rahul Bhattacharjee
Name of the Project/ Scene : Boz inside the train
Link of Project/Scene : https://rahuldecoded.github.io/

**Comment by shahbaz17** [comment]
Thanks all for reporting :+1: This is now featured on https://wiki.mozilla.org/India/WebVR/#Scenes.2FProjects_by_contributors
