### ISSUE TITLE
WebVR India in Media November 2016 (blog posts / event reports / tweets)

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#12]
This issue is created to report contributions done by volunteers in this month. If you have wrote a blogpost please follow the following format while reporting : 

**Name : 
Blog Title : 
Blog Link / tweets link :**

**Comment by vibhanshuchaudhary** [comment]
**Name :** Vibhanshu Chaudhary
**Blog Title :** A Day of Virtual Reality
**Blog Link :** https://vibhanshuchaudhary.wordpress.com/2016/11/10/a-day-of-virtual-reality/

**Comment by varadekd** [comment]
Name : MozVR Camp Bhopal
Blog Title : #include(Hash Include)
Blog Link / tweets link : https://blogcoherent.wordpress.com/2016/11/12/include/

**Comment by shahbaz17** [comment]
**Name** : Md Shahbaz Alam
**Blog Title** : MozDev @ NIIT
**Blog Link** : https://alamshahbaz.wordpress.com/2016/11/14/mozdev-niit/
**Tweet Link** : https://twitter.com/mdsbzalam/status/797426391738413057

**Comment by Srushtika** [comment]
Talk about WebVR and A-Frame in GDG DevFest at Google, Blr : https://www.youtube.com/watch?v=KxZ5q8CPQm4
Featured on A week of A-frame: https://aframe.io/blog/awoa-31-32/
Tweets: 
1. https://twitter.com/Srushtika/status/789890602678628352
2. https://twitter.com/Srushtika/status/789723775453437952
3. https://twitter.com/Srushtika/status/787398391827468288
4. https://twitter.com/mozTechSpeakers/status/787310611139026945
5. https://twitter.com/mozTechSpeakers/status/787359004150292480

**Comment by rahuldecoded** [comment]
Name: WebVR at InfoCon.
Here me and Biraj Karmakar presented the knowledge of VR to the guests over there. Biraj Karmakar was demonstration the concepts of webVR and AFrame, where I was dealing with the code(in which very few people were interested :p)
.
Tweets: 

1. https://twitter.com/birajkarmakar/status/799494220297932800 
2. https://twitter.com/joininfocon/status/799512017489055744
3. https://twitter.com/joininfocon/status/799484438405062656

**Comment by rahuldecoded** [comment]
Name: WebVR at UIT
Here me and Biraj Karmakar presented the knowledge of VR. Biraj Karmakar was demonstration the concepts of webVR and AFrame, where I was showing little bit of hand-ons under the guidance of Biraj Karmakar

Blog: https://rahuldecoded.wordpress.com/2016/12/06/mozactivate-tour-1-university-institute-of-technology-burdwan/

Tweets: https://twitter.com/birajkarmakar/status/802416382214164480
https://twitter.com/birajkarmakar/status/802395895794782208

Reps Link: https://reps.mozilla.org/e/mozactivate-tour/

**Comment by shahbaz17** [comment]
Thanks all for reporting :+1: This is now featured on https://wiki.mozilla.org/India/WebVR/#Blogposts.2FReports
