### ISSUE TITLE
Projects/Scenes created in December 2016

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#15]
This issue is created to report contributions done by volunteers in this month. While sharing your scenes/projects with us, please follow the following format :

**Name :**
**Name of Project / Scene :**
**Link of Project / Scene :**

**Comment by mukeshpathak345** [comment]
Name: Mukesh Pathak
Name of Project/Scene: Merry Christmas
Link of Project/Scene: https://mukeshpathak345.github.io/Merry-Christmas/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak
Name of Project / Scene : Sun-Shine
Link of Project / Scene :  https://mukeshpathak345.github.io/sunshine/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak
Name of Project / Scene : Happy New Year
Link of Project / Scene : https://mukeshpathak345.github.io/New-year-2017/
