### ISSUE TITLE
WebVR India in Media December 2016 (blog posts / event reports / tweets)

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/volunteer-contributions#17]
This issue is created to report contributions done by volunteers in this month. If you have wrote a blogpost please follow the following format while reporting :

**Name :
Blog Title :
Blog Link / tweets link :**

**Comment by mukeshpathak345** [comment]
Blog Month: November 2016
Name : Mukesh Pathak  
Blog Title : MozVR Camp Bhopal @FxLNCT
Blog Link / tweets link : https://mikebhopal.wordpress.com/2016/11/23/mozvr-camp-bhopal-fxlnct/
