### ISSUE TITLE
WebVR India in Media January 2017 (blog posts / event reports / tweets)

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#18]
This issue is created to report contributions done by volunteers in this month. If you have written a blogpost please follow the following format while reporting :

**Name :
Blog Title :
Blog Link / tweets link :**

**Comment by mukeshpathak345** [comment]
Name :Mukesh Pathak Mike
Blog Title : WebVR Camp IET-DAVV Indore M.P.
Blog Link / tweets link https://mikebhopal.wordpress.com/2017/01/23/mozvr-camp-iet-davv-indore/

**Comment by gurumukhi** [comment]
Thanks @mukeshpathak345
