### ISSUE TITLE
Events conducted in January 2017

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#19]
This issue is created to report contributions done by volunteers in this month. While reporting your event please use the following format:

**Name :
Event Name :
Event Date :
Event Location :
Event Link :**

**Comment by vyaspranjal33** [comment]
Name : Pranjal Vyas
Event Name : A Day Of Virtual Reality
Event Date : 19th january 2017
Event Location : Sir BPTI campus,Bhavnagar,Gujarat
Event Link : https://reps.mozilla.org/e/a-day-of-virtual-reality-1/ , https://pranjalvyas.wordpress.com/2017/01/21/a-day-of-virtual-reality/

**Comment by mradul2601** [comment]
Name : Pranjal Vyas
Event Name : A Day Of Virtual Reality
Event Date : 20th january 2017
Event Location : IET DAVV,Indore
Event Link : https://reps.mozilla.org/e/mozvr-camp-indore/
https://mradulgargblog.wordpress.com/2017/01/29/webvr-hands-oniet-davv/

**Comment by mukeshpathak345** [comment]
Name : Mukesh Pathak
Event Name : MozActivate @ BSSS
Event Date : 3rd March 2017
Event Location : BSSS College Bhopal Madhya Pradesh
Event Link : https://mikebhopal.wordpress.com/2017/03/06/webvr-session-in-bsss/

**Comment by gurumukhi** [comment]
Thanks @vyaspranjal33 & @mradul2601 for the event. @mukeshpathak345 I have added ur event to https://github.com/webvr-india/volunteer-contributions/issues/26.
