### ISSUE TITLE
Projects/Scenes created in September 2016

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#2]

**Comment by shahbaz17** [comment]
Name of Event : Virtual Day @ MozUnicorn
Date : 09 Sept.,2016.
Scenes Created : https://mozunicorn.github.io/MozUnicorn-s-VirtualDay/

**Comment by Srushtika** [comment]
A-Frame tags used: <a-box>,<a-sky>,<a-camera>,<a-assets>
Date: 10th Sept '16
Scene Link: https://srushtika.github.io/mywebvr/Scene%201/index.html

**Comment by Srushtika** [comment]
A-Frame tags used: a-obj-model, a-cone, a-sphere, a-sky, a-assets, a-box
Date: 12th Sept '16
Scene Link: https://srushtika.github.io/mywebvr/Scene%202/index.html

**Comment by Srushtika** [comment]
A-Frame tags used: a-assets, a-videosphere
Date: 24th Sept '16
Scene Link: https://srushtika.github.io/mywebvr/Scene%203/index.html

**Comment by vibhanshu95** [comment]
**A-Frame tags used :** a-cone, a-sphere, a-sky, a-cylinder
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene1.html

**Comment by vibhanshu95** [comment]
**A-Frame tags used :** a-cube, a-cylinder, a-sphere, a-sky
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene2.html

**Comment by vibhanshu95** [comment]
**A-Frame tags used :** a-assets, a-curvedimage
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene3.html

**A-Frame tags used :** a-sky, 360 Degree image, a-box
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene4.html

**A-Frame tags used :** a-video, a-assets, a-sky
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene5.html

**Comment by vibhanshu95** [comment]
**A-Frame tags used :**  a-assets, a-sky, a-entity, a-animation
**Month :** September' 16
**Scene Link :** https://vibhanshu95.github.io/MyVR/scene6.html

**Comment by gurumukhi** [comment]
@vibhanshuchaudhary looks like you have provided incorrect urls, but dont worry I found the correct urls - they are like https://vibhanshuchaudhary.github.io/MyVR/scene1.html.

**Comment by gurumukhi** [comment]
https://vibhanshuchaudhary.github.io/MyVR/scene5.html - This hasn't worked properly. This looks like a 360 video, but it is being shown as a normal video. May be you can check code of similar scene created by @Srushtika where she has shown a 360 video in VR correctly.

**Comment by gurumukhi** [comment]
https://vibhanshuchaudhary.github.io/MyVR/scene6.html - @vibhanshuchaudhary looks like the ASWD controls are disabled for this scene's camera. Was that intentional?

**Comment by gurumukhi** [comment]
Great work @shahbaz17 @vibhanshuchaudhary @Srushtika, keep it up. Thanks for reporting 👍
