### ISSUE TITLE
Projects/Scenes created in Feb 2017

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/volunteer-contributions#21]
This issue is created to report contributions done by volunteers in this month. While sharing your scenes/projects with us, please follow the following format :

Name :
Name of Project / Scene :
Link of Project / Scene :
Title / Summary / Remarks:

**Comment by devilsown111** [comment]
NAME : RONIL PATEL
NAME OF PROJECT : WAITING FOR THE BALL 2 BOUNCE ON THE CYLINDERzz
REMARKS : FOOTPRINTS @MSU 2K17
LINK : https://devilsown111.github.io/vr/ronilpatel.html

**Comment by karanjoshi** [comment]
Name:Karan Joshi
Name of Project : background and shapes
Link: https://gist.github.com/karanjoshi/e82ce5fdc79c90ce388ae910988961b1
Remarks: footprint 2017

**Comment by abhinavbaldha** [comment]
NAME:Abhinav baldha
name of project: 'HELLO.' using blocks.
Link: [](https://abhinavbaldha.github.io/webVR1/vr5.html)
remarks: Footprints 2017

**Comment by abhinavbaldha** [comment]
NAME: ABHINAV BALDHA
Name of Project: 'HELLO.' using blocks
link: https://abhinavbaldha.github.io/webVR1/vr5.html
remarks: Footprints 2017

**Comment by chavdaamitk** [comment]
Name : Amit Chavda
Name Of Project : vr
Link : https://gist.github.com/chavdaamitk/cc4f36e85c22b49a572adb54ec2d311b
Remarks : FootPrintsX7

**Comment by MadhuriQA** [comment]
Name : Madhuri Mittal
Name of Project / Scene : WebVR
Link of Project / Scene : https://github.com/MadhuriQA/WebVR
Title / Summary / Remarks: Footprints 2017

**Comment by gurumukhi** [comment]
Other people who submitted code during Footprints 2017 -
@chauhanjay
@DarshanAjudiya
@bhavaya
@shahsamarthr 

Thanks all!

**Comment by gurumukhi** [comment]
Event conducted: Footprint 2017 | https://reps.mozilla.org/e/footprints-2017/

**Comment by gurumukhi** [comment]
@jerryjagtap55 can you use aframe tags to create something?

**Comment by gurumukhi** [comment]
@karanjoshi can you also provide the link of the output of your scene (use github pages). Provide link on current month's open issue to get this added to mozilla wiki.

**Comment by gurumukhi** [comment]
Linked added at https://wiki.mozilla.org/India/WebVR/
