### ISSUE TITLE
bhavya

### ISSUE THREAD

**Issue by bhavaya** [webvr-india/volunteer-contributions#23]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, World! • A-Frame</title>

      <a-entity position="0 0 3.8">
        <a-camera></a-camera>
      </a-entity>
    </a-scene>
	
  </body>
</html>

**Comment by gurumukhi** [comment]
Thanks @bhavaya ! Can you try creating a webpage and upload it on your github account? Let me know if you need any help :-)
