### ISSUE TITLE
Darshan

### ISSUE THREAD

**Issue by DarshanAjudiya** [webvr-india/volunteer-contributions#24]
<!DOCTYPE html>
<html>
  <head>
	
    <title></title>
    <meta name="description" content="Hello, World! • A-Frame">
    <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>

    <a-text value="h  e  l  l  o"  width="100px" height="10px" position="2 1 3"  rotation="0 120 0" depth="20px"></a-text>
	.  <a-curvedimage src="IMAGE1.png" height="3.0" radius="5.7" theta-length="72"
                 rotation="0 100 0" scale="0.4 1 0.9"></a-curvedimage>>
	
	<a-assests><img id="sc" src="fnt.jpg" ></a-assests>
      <a-sky src="#sc" rotation="20 -130 0"></a-sky>
      <a-entity position="0 0 3.8">
        <a-camera></a-camera>
      </a-entity>
    </a-scene>
  </body>
</html>

**Comment by gurumukhi** [comment]
Thanks @DarshanAjudiya  ! Can you try creating a webpage and upload it on your github account? Let me know if you need any help :-)
