### ISSUE TITLE
jaynish

### ISSUE THREAD

**Issue by chauhanjay** [webvr-india/volunteer-contributions#25]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, World! • A-Frame</title>
    <meta name="description" content="Hello, World! • A-Frame">
    <script src="https://aframe.io/releases/0.3.2/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>

      <a-sphere position="19 1.25 5" radius="1.25" color="#EF2D5E"></a-sphere>
      <a-box position="-9 1 5" rotation="0 45 0" width="3" height="3" depth="1"  color="#4CC3D9"></a-box>
      <a-cylinder position="1 0.75 1" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
      

      <a-sky color="#ECECEC"></a-sky>
      <a-entity position="0 0 3.8">
        <a-camera></a-camera>
      </a-entity>
    </a-scene>
  </body>
</html>

**Comment by gurumukhi** [comment]
Thanks @chauhanjay ! Can you try creating a webpage and upload it on your github account? Let me know if you need any help :-)
