### ISSUE TITLE
Contributions from April 2017

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/volunteer-contributions#28]
This issue is created to report contributions done by volunteers in this month. While sharing your scenes/projects with us, please follow the following format -

Name :
Title/Summary of Project / Scene :
Link of Project / Scene :
Remark:

OR

Name :
Event Name :
Event Date :
Event Location :
Event Link :

OR

Name:
Blog/Tweet/Article link:
Summary of your media/social media coverage:

**Comment by robinkoshy** [comment]
Robin Koshy
MozVR
https://robinkoshy.github.io/MozVR/
A basic frame for a virtual reality experience.

**Comment by robinkoshy** [comment]
Robin Koshy
MozActivate @BSSS
3rd March 2017
Bhopal
http://robinmozilla.blogspot.in/2017/03/v-behaviorurldefaultvmlo.html?m=1

**Comment by akshit13** [comment]
Name : Akshit Sharma
Event Name : WebVR Camp at Chandigarh University
Event Date : 25/4/2017
Event Location : Chandigarh University, Punjab
Event Link : https://reps.mozilla.org/e/webvr-camp-at-chandigarh-university/

https://twitter.com/Akshit_13/status/857185232864325636

**Comment by gurumukhi** [comment]
Thanks @robinkoshy & @akshit13 :-) You are now featured on https://wiki.mozilla.org/India/WebVR/. You will also be added to the Superstars telegram group!

**Comment by viswanathamsantosh** [comment]
Conference: Fossasia
Talk recording link: https://www.youtube.com/watch?v=e4HbnJ_-u0o&feature=youtu.be&t=2m4s
Slides link: https://slides.com/isantoshv/webvr-fossasia

**Comment by viswanathamsantosh** [comment]
Hey @gurumukhi , Sorry for being late. Added my contributions just now. :)

**Comment by viswanathamsantosh** [comment]
and my Blogpost: https://isantoshv.wordpress.com/2017/03/24/speaking-at-fossasia-2017/
