### ISSUE TITLE
WebVR India in Media, September 2016 (blog posts / event reports / tweets)

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#3]

**Comment by shahbaz17** [comment]
Name of Event : Virtual day @ Mozunicorn
Date : 09 Sept. , 2016
Reps Portal link : https://reps.mozilla.org/e/virtual-day-mozunicorn/
Blog Link : https://alamshahbaz.wordpress.com/2016/09/18/mozunicorns-virtual-day/

**Comment by gurumukhi** [comment]
https://gurumukhi.wordpress.com/2016/09/21/a-frame-experience/
https://gurumukhi.wordpress.com/2016/09/21/a-frame-for-vr-development-on-web/

**Comment by Srushtika** [comment]
First Blog Post: http://la-mia-squadra.blogspot.in/2016/09/a-month-of-frame.html
24th Sept '16

**Comment by vibhanshu95** [comment]
**Blog Post on WebVR ( My experience + Basic tutorial )  :**                                https://vibhanshuchaudhary.wordpress.com/2016/10/01/road-to-webvr-using-mozvr-a-frame/ 

Any suggestions are most welcomed.

**Comment by gurumukhi** [comment]
Thanks @vibhanshuchaudhary @Srushtika @shahbaz17 for winning the contest. Your work has been listed on https://wiki.mozilla.org/India/WebVR/.
