### ISSUE TITLE
Work done during Hack Night India

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/volunteer-contributions#30]
Kindly report here all contribution done by you during https://reps.mozilla.org/e/a-frame-hack-night-india/.

**Comment by mukeshpathak345** [comment]
https://mukeshpathak345.github.io/Aframe-Hack-Night/

Robin Koshy And Mukesh Pathak Created a scene For Aframe HackNight WebVR India

**Comment by vibhanshuchaudhary** [comment]
https://vibhanshuchaudhary.github.io/HackNightIndia/hacknight.html

https://vibhanshuchaudhary.github.io/HackNightIndia/hacknight1.html

**Comment by reddyes** [comment]
https://github.com/reddyes/hackathon-Webvr

**Comment by ritesh07raj** [comment]
WebVR HackNight.
Large file attached so it takes time to load.

https://ritesh07raj.github.io/demo/

**Comment by robinkoshy** [comment]
Work done during Hack Night India
https://mukeshpathak345.github.io/Aframe-Hack-Night/
https://github.com/robinkoshy/Aframe-Hack-Night

**Comment by gurumukhi** [comment]
@mukeshpathak345 & @robinkoshy : Can you guys please convert this scene into a-frame scene? Let me know if you have any doubt here.

**Comment by gurumukhi** [comment]
Good work @vibhanshuchaudhary & @ritesh07raj  :-) 👍

**Comment by gurumukhi** [comment]
@reddyes can you please convert this into github pages and put here link of published webpage directly?

You need to go to settings of repo and select master branch as source under 'GitHub Pages' section. Then you will get published pages link in the same section. Detailed info at https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ & https://help.github.com/categories/github-pages-basics/

**Comment by reddyes** [comment]
@gurumukhi  done

**Comment by ritesh07raj** [comment]
Thank you @gurumukhi

**Comment by gurumukhi** [comment]
@reddyes link plz?

**Comment by reddyes** [comment]
@gurumukhi  https://reddyes.github.io/hackathon-Webvr.io/

**Comment by withshubh** [comment]
https://withshubh.github.io/A-frame-HackNight/

**Comment by withshubh** [comment]
https://withshubh.github.io/A-frame-HackNight/

**Comment by gurumukhi** [comment]
Scenes submitted :
* @vibhanshuchaudhary  - https://vibhanshuchaudhary.github.io/HackNightIndia/hacknight.html
* @vibhanshuchaudhary  - https://vibhanshuchaudhary.github.io/HackNightIndia/hacknight1.html
* @reddyes - https://reddyes.github.io/hackathon-Webvr.io/
* @ritesh07raj - https://ritesh07raj.github.io/demo/
* @withshubh - https://withshubh.github.io/A-frame-HackNight/
* @mukeshpathak345  & @robinkoshy - https://mukeshpathak345.github.io/Aframe-Hack-Night/ [Not eligible as the is not build using aframe]

Other than this @shahbaz17 & @viswanathamsantosh worked on website (Sumantro helped with design too) - http://github.com/webvr-india/webvr-india.github.io/

**Comment by gurumukhi** [comment]
Thanks everyone for your valuable contributions and involvement in Hack Night. All of you are involved with WebVR India community since a long time and I would like to personally like to thank you for your involvement in making this an awesome community.

Out of all submitted scenes, @vibhanshuchaudhary's scene (https://vibhanshuchaudhary.github.io/HackNightIndia/hacknight.html) & @reddyes's scene (https://reddyes.github.io/hackathon-Webvr.io/) really stand out. You guys have tried out different things in your scenes which is really cool. I would like to specially mention the completeness of your scenes. Congratulations to both of you (you will soon receive a mail from me asking your address to ship the gifts :1st_place_medal:), and once again thanks to all of you for you contributions. There are many amazing contests and activities lined up for you in upcoming days and months, you will hear about them on telegram soon and we are sure you will love them too.

**Comment by shahbaz17** [comment]
Congratulations @vibhanshuchaudhary and @reddyes

**Comment by vibhanshuchaudhary** [comment]
**Thank you** @gurumukhi and @shahbaz17 !

> I

 will always be proud to be a contributor of such an amazing community(WebVR India) that is working towards future paradigm shift i.e., **Virtual Reality**. 

>

**Comment by vibhanshuchaudhary** [comment]
**Thank you** @gurumukhi and @shahbaz17 !

I will always be proud to be a contributor of such an amazing community (WebVR India) that is working towards future paradigm shift i.e., **Virtual Reality**.

**Comment by reddyes** [comment]
Thank you @gurumukhi  @shahbaz17  

@gurumukhi @tushararora  you are the main people who engaged me into open source community,coding  and vr .
special thanks to santosh for engaging me into website and teaching me about gibhub importance .
also harsha you have pushed me into another level 
thank you every one

**Comment by mukeshpathak345** [comment]
@mukeshpathak345 & @robinkoshy - https://mukeshpathak345.github.io/A-frame-hacknight/
Work done during Hack Night India

**Comment by gurumukhi** [comment]
Thanks @mukeshpathak345 & @robinkoshy , good work! Looks like everyone is liking the rain fountains too much :-D

Thanks @reddyes, we are really delighted to have you in the community.

Again, thanks everyone for you amazing work, closing this issue. And yes, dont forget to join us in today's monthly call in evening.. see you in telegram group and in the call.
