### ISSUE TITLE
Collecting contributions from May-Sept 2017

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/volunteer-contributions#32]
This issue is created to report contributions done by volunteers in this month. While sharing your scenes/projects with us, please follow the following format -

Name :
Title/Summary of Project / Scene :
Link of Project / Scene :
Remark:

OR

Name :
Event Name :
Event Date :
Event Location :
Event Link :

OR

Name:
Blog/Tweet/Article link:
Summary of your media/social media coverage:

**Comment by gurumukhi** [comment]
Name : Ram

Contribution-
Fixed an issue: https://github.com/aframevr/aframe/issues/2633

**Comment by reddyes** [comment]
Name : Sai Rajasekhar reddy
Title/Summary of Project / Scene : solar system
Link of Project / Scene : https://github.com/reddyes/hackathon-Webvr.io
Event Date :22 april 2017
Event Location : collab house

**Comment by reddyes** [comment]
Name :Sai Rajasekhar Reddy
Title/Summary of Project / Scene : atom (element)
Link of Project / Scene : https://github.com/reddyes/aframeRAY
Remark: 1st  web vr camp hyderabad

**Comment by reddyes** [comment]
Name: Sai Rajasekhar Reddy
contribution:  for website at hackNight hyderabad
link: https://github.com/reddyes/webvr-india.github.io

**Comment by Bornfromashes** [comment]
Name: Amit Kumar Singh
title/Summary of project/scene: SastiMasti(https://bornfromashes.github.io/sastimasti/)
Link of Project/Scene: https://github.com/Bornfromashes/sastimast
contribution: demo for talk on vr
event date: 8th april 2017
event location: AIT Pune
Blog/tweet/articlelink: https://tusharchoudhary.github.io/A-Frame-talk/
Remark: Talk at AIT-Pune Mozilla Community

**Comment by racmeh** [comment]
Name: Rachit Mehrotra
Title/Summary of Project / Scene: Universe and its planets
Link of Project / Scene: https://racmeh.github.io/ar_vr/
Remark: Made it using spheres animation and sky property with high quality images

**Comment by Jyothirmaikottu** [comment]
Name : Jyothirmai Kottu
Title/Summary of Project / Scene : Christmas Scene
Link of Project / Scene : https://jyothirmaikottu.gitlab.io/Christmas/
Remark: A simple Christmas project!

**Comment by Jyothirmaikottu** [comment]
Name : Jyothirmai Kottu 
Title/Summary of Project / Scene : Solarsystem
Link of Project / Scene : https://jyothirmaikottu.gitlab.io/chirstmas/

**Comment by mukeshpathak345** [comment]
All Issue update plz Close the issue

**Comment by gurumukhi** [comment]
Thanks all for you amazing contributions. Special mention to @Bornfromashes for his super funny implementation :-D All must have a look at his VR song once :-D

Your contribution has been updated at https://wiki.mozilla.org/India/WebVR/ (let us know if case we missed anything).
