### ISSUE TITLE
 WebVR India in Media October 2016 (blog posts / event reports / tweets) 

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#4]

**Comment by mradul2601** [comment]
following blogpost is the event report on the WebVR seminar on 8th october 2016

https://mradulgargblog.wordpress.com/

**Comment by shubhamgeete** [comment]
following blogpost are report for my recent events 

https://shubhamgeete.wordpress.com/2016/10/10/webvr-and-introduction-to-mozilla-invento2k16/

https://shubhamgeete.wordpress.com/2016/09/25/first-webvr-talk-connected-device-indore

https://shubhamgeete.wordpress.com/2016/09/26/webvr-hands-on-iit-indore/

**Comment by mradul2601** [comment]
https://mradulgargblog.wordpress.com/
Following blog is the event report of Introduction to WebVR Seminar on 17th October at IET DAVV .

**Comment by shahbaz17** [comment]
Hello @mradul2601 , can you give the full link of the blog ? since it's your blog address and for a specific blog i need to search the whole blog.

**Comment by mradul2601** [comment]
Hello @shahbaz17 ,Following are the blog links :                                                https://mradulgargblog.wordpress.com/2016/10/12/first-blog-post/
https://mradulgargblog.wordpress.com/2016/10/17/introduction-to-webvriet-davv/
