### ISSUE TITLE
Events conducted in October 2016

### ISSUE THREAD

**Issue by tushararora** [webvr-india/volunteer-contributions#6]

**Comment by shubhamgeete** [comment]
following blogpost are from my past  contribution on WebVR

https://shubhamgeete.wordpress.com/2016/10/10/webvr-and-introduction-to-mozilla-invento2k16/

**Comment by shubhamgeete** [comment]
https://shubhamgeete.wordpress.com/2016/09/25/first-webvr-talk-connected-device-indore/

**Comment by shubhamgeete** [comment]
https://shubhamgeete.wordpress.com/2016/09/26/webvr-hands-on-iit-indore/

**Comment by mradul2601** [comment]
following blogpost is the event report on the WebVR seminar

https://mradulgargblog.wordpress.com/

**Comment by Srushtika** [comment]
Talk on WebVR and Aframe VR at GDG DevFest '16 at Google, Blr, India https://www.youtube.com/watch?v=KxZ5q8CPQm4

**Comment by gurumukhi** [comment]
https://gurumukhi.wordpress.com/2016/10/20/vr-camp-event/

**Comment by shahbaz17** [comment]
Thanks @all for reporting :+1: This is now featured on https://wiki.mozilla.org/India/WebVR/.
