### ISSUE TITLE
Talked about WebVR at Science Hack Day India

### ISSUE THREAD

**Issue by lavish205** [webvr-india/volunteer-contributions#8]
@sumantro93 and I organized a hands-on workshop on WebVR at Science Hack Day India.
Hong Phuc Dang, Managing Director of FOSSASIA attended our workshop and was very impressed with how easily we can make VR contents with HTML and A-Frame.

**Comment by lavish205** [comment]
Photos: https://goo.gl/photos/E85r1W7Y8WEXNjtG9

**Comment by gurumukhi** [comment]
@lavish205 please add in existing issue created for the current month, no need to create new issue :-) Cool work bdw 👍

**Comment by shahbaz17** [comment]
Thanks @lavish205  for reporting :+1: This is now featured on https://wiki.mozilla.org/India/WebVR/.

**Comment by shahbaz17** [comment]
@lavish205 can you close this issue ?

**Comment by lavish205** [comment]
Please add Sumantro name on wiki page.

**Comment by shahbaz17** [comment]
Ok doing that. Thanks for reporting
